### ISSUE TITLE
Targeted-Meta-Learning code

### ISSUE THREAD

**Issue by zhujiem** [mmkamani7/SkeletonMatching#1]
Sorry for disturbing, but will you release the code for Targeted-Meta-Learning soon. I am very interest in your work, and want to apply the code to try on my dataset. I am currently not sure how to implement the auto-gradient of the outer model, especially when the inner model updates for t_in steps. Could you please provide a code snippet if possible. Thank you!

https://github.com/mmkamani7/Targeted-Meta-Learning

**Comment by mmkamani7** [comment]
I will make it online in two weeks hopefully. Will email you when it is ready.

**Comment by zhujiem** [comment]
Hi Mohammad, is the code ready? I am standing waiting for your wonder project~

**Comment by mmkamani7** [comment]
Sorry for such a delay, but I pushed the code to the public repo here: https://github.com/mmkamani7/Targeted-Meta-Learning
The code has been developed on Tensorflow 1.x API, but I have adapted it to Tensorflow 2.x API. Now it can be run on Tensorflow 2.x without a problem.

**Comment by zhujiem** [comment]
Thank you so much for your sharing：）
